name: 'Terraform CI/CD'

on:
  push:
    branches:
    - main
    paths-ignore:
     - '.github\workflow\**'
   

  permissions:
     contents: -read

  ## env:
    ## AWS_REGION: ${{}}

Jobs:
  Terraform:
    name: Terraform
    runs-on: Windows-latest

    defaults:
      run: 
        shell: bash


    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure-AWS-Credentials
      uses: aws-actions/configure-aws-credentials@v2

      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-key: ${{secrets.AWS_SECRET_KEY}}

    - name: Setup-Terraform
      uses: harshicorp/setup-terraform@v2

      with:
        terraform_version: "1.5.0"

    - name: Terraform-Format
      id: Fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: Init
      run: terraform Init

    - name: Terraform Validate
      id: Validate
      run: terraform validate

    - name: Terraform plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan
      continue-on-error: true

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref == 'refs/head/master' && github.event_name == 'push'
      run: terraform apply -auto-approve

     